"""create_all_tables

Revision ID: a70e686adc4e
Revises: 8788af0e2740
Create Date: 2026-03-26 19:06:38.520272

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import models.base


# revision identifiers, used by Alembic.
revision: str = "a70e686adc4e"
down_revision: Union[str, Sequence[str], None] = "8788af0e2740"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "edge_property_definition",
        sa.Column("id", models.base.GUID(), nullable=False),
        sa.Column(
            "edge_property_definition_identifier", sa.String(length=255), nullable=False
        ),
        sa.Column(
            "edge_property_definition_name", sa.String(length=255), nullable=False
        ),
        sa.Column("edge_property_definition_description", sa.String(), nullable=True),
        sa.Column(
            "edge_property_definition_type", sa.String(length=50), nullable=False
        ),
        sa.Column("edge_property_definition_default_value", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column(
            "created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_by", sa.String(length=255), nullable=True),
        sa.Column("modified_on", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_edge_property_definition_edge_property_definition_identifier"),
        "edge_property_definition",
        ["edge_property_definition_identifier"],
        unique=True,
    )
    op.create_table(
        "edge_type",
        sa.Column("id", models.base.GUID(), nullable=False),
        sa.Column("edge_type_identifier", sa.String(length=255), nullable=False),
        sa.Column("edge_type_name", sa.String(length=255), nullable=False),
        sa.Column("edge_type_description", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column(
            "created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_by", sa.String(length=255), nullable=True),
        sa.Column("modified_on", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_edge_type_edge_type_identifier"),
        "edge_type",
        ["edge_type_identifier"],
        unique=True,
    )
    op.create_table(
        "node_property_definition",
        sa.Column("id", models.base.GUID(), nullable=False),
        sa.Column(
            "node_property_definition_identifier", sa.String(length=255), nullable=False
        ),
        sa.Column(
            "node_property_definition_name", sa.String(length=255), nullable=False
        ),
        sa.Column("node_property_definition_description", sa.String(), nullable=True),
        sa.Column(
            "node_property_definition_type", sa.String(length=50), nullable=False
        ),
        sa.Column("node_property_definition_default_value", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column(
            "created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_by", sa.String(length=255), nullable=True),
        sa.Column("modified_on", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_node_property_definition_node_property_definition_identifier"),
        "node_property_definition",
        ["node_property_definition_identifier"],
        unique=True,
    )
    op.create_table(
        "node_type",
        sa.Column("id", models.base.GUID(), nullable=False),
        sa.Column("node_type_identifier", sa.String(length=255), nullable=False),
        sa.Column("node_type_name", sa.String(length=255), nullable=False),
        sa.Column("node_type_description", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column(
            "created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_by", sa.String(length=255), nullable=True),
        sa.Column("modified_on", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_node_type_node_type_identifier"),
        "node_type",
        ["node_type_identifier"],
        unique=True,
    )
    op.create_table(
        "edge_type_property_assignment",
        sa.Column("id", models.base.GUID(), nullable=False),
        sa.Column("edge_type_id_fk", models.base.GUID(), nullable=False),
        sa.Column("edge_property_definition_id_fk", models.base.GUID(), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("default_value", sa.String(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column(
            "created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_by", sa.String(length=255), nullable=True),
        sa.Column("modified_on", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["edge_property_definition_id_fk"],
            ["edge_property_definition.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["edge_type_id_fk"], ["edge_type.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "edge_type_id_fk",
            "edge_property_definition_id_fk",
            name="uq_edge_type_property",
        ),
    )
    op.create_index(
        op.f("ix_edge_type_property_assignment_edge_property_definition_id_fk"),
        "edge_type_property_assignment",
        ["edge_property_definition_id_fk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_edge_type_property_assignment_edge_type_id_fk"),
        "edge_type_property_assignment",
        ["edge_type_id_fk"],
        unique=False,
    )
    op.create_table(
        "node",
        sa.Column("id", models.base.GUID(), nullable=False),
        sa.Column("node_type_id_fk", models.base.GUID(), nullable=False),
        sa.Column("node_identifier", sa.String(length=255), nullable=False),
        sa.Column("node_name", sa.String(length=255), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column(
            "created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_by", sa.String(length=255), nullable=True),
        sa.Column("modified_on", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["node_type_id_fk"], ["node_type.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_node_node_identifier"), "node", ["node_identifier"], unique=True
    )
    op.create_index(
        op.f("ix_node_node_type_id_fk"), "node", ["node_type_id_fk"], unique=False
    )
    op.create_table(
        "node_type_property_assignment",
        sa.Column("id", models.base.GUID(), nullable=False),
        sa.Column("node_type_id_fk", models.base.GUID(), nullable=False),
        sa.Column("node_property_definition_id_fk", models.base.GUID(), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("default_value", sa.String(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column(
            "created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_by", sa.String(length=255), nullable=True),
        sa.Column("modified_on", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["node_property_definition_id_fk"],
            ["node_property_definition.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["node_type_id_fk"], ["node_type.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "node_type_id_fk",
            "node_property_definition_id_fk",
            name="uq_node_type_property",
        ),
    )
    op.create_index(
        op.f("ix_node_type_property_assignment_node_property_definition_id_fk"),
        "node_type_property_assignment",
        ["node_property_definition_id_fk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_node_type_property_assignment_node_type_id_fk"),
        "node_type_property_assignment",
        ["node_type_id_fk"],
        unique=False,
    )
    op.create_table(
        "edge",
        sa.Column("id", models.base.GUID(), nullable=False),
        sa.Column("edge_type_id_fk", models.base.GUID(), nullable=False),
        sa.Column("edge_identifier", sa.String(length=255), nullable=False),
        sa.Column("edge_name", sa.String(length=255), nullable=False),
        sa.Column("source_node_id_fk", models.base.GUID(), nullable=False),
        sa.Column("target_node_id_fk", models.base.GUID(), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column(
            "created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_by", sa.String(length=255), nullable=True),
        sa.Column("modified_on", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["edge_type_id_fk"], ["edge_type.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["source_node_id_fk"], ["node.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_node_id_fk"], ["node.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_edge_edge_identifier"), "edge", ["edge_identifier"], unique=True
    )
    op.create_index(
        op.f("ix_edge_edge_type_id_fk"), "edge", ["edge_type_id_fk"], unique=False
    )
    op.create_index(
        op.f("ix_edge_source_node_id_fk"), "edge", ["source_node_id_fk"], unique=False
    )
    op.create_index(
        op.f("ix_edge_target_node_id_fk"), "edge", ["target_node_id_fk"], unique=False
    )
    op.create_table(
        "node_property_value",
        sa.Column("id", models.base.GUID(), nullable=False),
        sa.Column("node_id_fk", models.base.GUID(), nullable=False),
        sa.Column("node_property_definition_id_fk", models.base.GUID(), nullable=False),
        sa.Column("node_property_value", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column(
            "created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_by", sa.String(length=255), nullable=True),
        sa.Column("modified_on", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["node_id_fk"], ["node.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["node_property_definition_id_fk"],
            ["node_property_definition.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "node_id_fk",
            "node_property_definition_id_fk",
            name="uq_node_property_value",
        ),
    )
    op.create_index(
        op.f("ix_node_property_value_node_id_fk"),
        "node_property_value",
        ["node_id_fk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_node_property_value_node_property_definition_id_fk"),
        "node_property_value",
        ["node_property_definition_id_fk"],
        unique=False,
    )
    op.create_table(
        "edge_property_value",
        sa.Column("id", models.base.GUID(), nullable=False),
        sa.Column("edge_id_fk", models.base.GUID(), nullable=False),
        sa.Column("edge_property_definition_id_fk", models.base.GUID(), nullable=False),
        sa.Column("edge_property_value", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(length=255), nullable=True),
        sa.Column(
            "created_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("modified_by", sa.String(length=255), nullable=True),
        sa.Column("modified_on", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["edge_id_fk"], ["edge.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["edge_property_definition_id_fk"],
            ["edge_property_definition.id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "edge_id_fk",
            "edge_property_definition_id_fk",
            name="uq_edge_property_value",
        ),
    )
    op.create_index(
        op.f("ix_edge_property_value_edge_id_fk"),
        "edge_property_value",
        ["edge_id_fk"],
        unique=False,
    )
    op.create_index(
        op.f("ix_edge_property_value_edge_property_definition_id_fk"),
        "edge_property_value",
        ["edge_property_definition_id_fk"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_edge_property_value_edge_property_definition_id_fk"),
        table_name="edge_property_value",
    )
    op.drop_index(
        op.f("ix_edge_property_value_edge_id_fk"), table_name="edge_property_value"
    )
    op.drop_table("edge_property_value")
    op.drop_index(
        op.f("ix_node_property_value_node_property_definition_id_fk"),
        table_name="node_property_value",
    )
    op.drop_index(
        op.f("ix_node_property_value_node_id_fk"), table_name="node_property_value"
    )
    op.drop_table("node_property_value")
    op.drop_index(op.f("ix_edge_target_node_id_fk"), table_name="edge")
    op.drop_index(op.f("ix_edge_source_node_id_fk"), table_name="edge")
    op.drop_index(op.f("ix_edge_edge_type_id_fk"), table_name="edge")
    op.drop_index(op.f("ix_edge_edge_identifier"), table_name="edge")
    op.drop_table("edge")
    op.drop_index(
        op.f("ix_node_type_property_assignment_node_type_id_fk"),
        table_name="node_type_property_assignment",
    )
    op.drop_index(
        op.f("ix_node_type_property_assignment_node_property_definition_id_fk"),
        table_name="node_type_property_assignment",
    )
    op.drop_table("node_type_property_assignment")
    op.drop_index(op.f("ix_node_node_type_id_fk"), table_name="node")
    op.drop_index(op.f("ix_node_node_identifier"), table_name="node")
    op.drop_table("node")
    op.drop_index(
        op.f("ix_edge_type_property_assignment_edge_type_id_fk"),
        table_name="edge_type_property_assignment",
    )
    op.drop_index(
        op.f("ix_edge_type_property_assignment_edge_property_definition_id_fk"),
        table_name="edge_type_property_assignment",
    )
    op.drop_table("edge_type_property_assignment")
    op.drop_index(op.f("ix_node_type_node_type_identifier"), table_name="node_type")
    op.drop_table("node_type")
    op.drop_index(
        op.f("ix_node_property_definition_node_property_definition_identifier"),
        table_name="node_property_definition",
    )
    op.drop_table("node_property_definition")
    op.drop_index(op.f("ix_edge_type_edge_type_identifier"), table_name="edge_type")
    op.drop_table("edge_type")
    op.drop_index(
        op.f("ix_edge_property_definition_edge_property_definition_identifier"),
        table_name="edge_property_definition",
    )
    op.drop_table("edge_property_definition")
    # ### end Alembic commands ###
